from schemas.series import SeriesSchema
from schemas.genre import GenreSchema
from schemas.series_genre import SeriesGenreSchema
from schemas.author import AuthorSchema
from schemas.series_author import SeriesAuthorSchema
from schemas.editorial import EditorialSchema
from schemas.edition import EditionSchema
from schemas.user import UserSchema
from schemas.user_series import UserSeriesSchema
from schemas.user_edition import UserEditionSchema
from schemas.user_volume import UserVolumeSchema